steps:
  - id: "Running Docker Compose"
    name: docker/compose
    args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
  - id: "Running Unit Tests"
    name: docker
    args: ['exec', '-t', 'go-hpa', 'go', 'test', './...']
  - id: 'Building Image for Production' 
    name: docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_GOLANG_FULLCYCLE_DESAFIO_K8S_HPA_NAME}:$SHORT_SHA', '.']
  - id: 'Pushing Image' 
    name: docker
    args: ['push', 'gcr.io/$PROJECT_ID/${_GOLANG_FULLCYCLE_DESAFIO_K8S_HPA_NAME}:$SHORT_SHA']
  - id: 'Set Builded Image at K8S Deployment File'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#andradereginaldo/go-hpa#gcr.io/$PROJECT_ID/${_GOLANG_FULLCYCLE_DESAFIO_K8S_HPA_NAME}:$SHORT_SHA#g' deployment.yaml > deployment.prod.yaml;
        cat deployment.prod.yaml;
  - id: 'Deploying K8S'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.prod.yaml'
    env:
      - '${_CLOUDSDK_COMPUTE_ZONE}'
      - '${_CLOUDSDK_CONTAINER_CLUSTER}'
  - id: 'Startup K8S Service'
    name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'apply'
      - '-f'
      - 'service.yaml'
    env:
      - '${_CLOUDSDK_COMPUTE_ZONE}'
      - '${_CLOUDSDK_CONTAINER_CLUSTER}'
  - id: 'Startup K8S HPA'
    name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'apply'
      - '-f'
      - 'hpa.yaml'
    env:
      - '${_CLOUDSDK_COMPUTE_ZONE}'
      - '${_CLOUDSDK_CONTAINER_CLUSTER}'
substitutions:
  _GOLANG_FULLCYCLE_DESAFIO_K8S_HPA_NAME: 'go-hpa'
  _CLOUDSDK_COMPUTE_ZONE: 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  _CLOUDSDK_CONTAINER_CLUSTER: 'CLOUDSDK_CONTAINER_CLUSTER=code-education-devops-golang'
images: ['gcr.io/$PROJECT_ID/${_GOLANG_FULLCYCLE_DESAFIO_K8S_HPA_NAME}']