apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hpa
      tier: frontend
  template:
    metadata:
      labels:
        app: go-hpa
        tier: frontend
    spec:
      containers:
      - name: go-hpa
        image: andradereginaldo/go-hpa
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "50m"
