FROM golang:1.14-alpine as builder
RUN apk add --no-cache upx build-base
WORKDIR /go/src/golang-fullcycle-desafio-k8s-hpa
COPY . .
RUN GOOS=linux go build -ldflags "-s -w" -tags netgo -a main.go
ENTRYPOINT ["./main"]